### ISSUE TITLE
Publish to pypi

### ISSUE THREAD

**Issue by eugenkleinschmidt** [stephrdev/conrad-relaycard#2]
It would be very nice to have this package in pypi.

I think renaming to have "conrad" in the name would also be good.

**Comment by stephrdev** [comment]
I like the idea. As soon as we have the Py3 upgrade merged I'm going to rename the repository to conrad-relaycard. We should also consider renaming the package then and also the cli entrypoint.

**Comment by eugenkleinschmidt** [comment]
#1 is done😁

**Comment by stephrdev** [comment]
https://pypi.org/project/conrad-relaycard/
